/**
 * Author: ChungBT
 * Action Constants
 */
module.exports = {
    SIGN_IN: 'SIGN_IN',
    SIGN_UP: 'SIGN_UP',
    GET_ALL_BOT: 'GET_ALL_BOT',
    ADD_NEW_BOT: 'ADD_NEW_BOT',
    UPDATE_BOT: 'UPDATE_BOT',
    DELETE_BOT: 'DELETE_BOT',
    GET_ALL_GROUP: 'GET_ALL_GROUP',
    ADD_NEW_GROUP: 'ADD_NEW_GROUP',
    UPDATE_GROUP: 'UPDATE_GROUP',
    DELETE_GROUP: 'DELETE_GROUP',
    GET_CONTENT_BLOCK: 'GET_CONTENT_BLOCK',
    ADD_NEW_BLOCK: 'ADD_NEW_BLOCK',
    UPDATE_NAME_BLOCK: 'UPDATE_NAME_BLOCK',
    UPDATE_ELEMENTS_BLOCK: 'UPDATE_ELEMENTS_BLOCK',
    DELETE_BLOCK: 'DELETE_BLOCK',
    TRANSFER_BLOCK: 'TRANSFER_BLOCK',
    GET_ALL_RULE: 'GET_ALL_RULE',
    ADD_NEW_RULE: 'ADD_NEW_RULE',
    UPDATE_RULE: 'UPDATE_RULE',
    DELETE_RULE: 'DELETE_RULE',
    CREATE_EMPTY_ELEMENT: 'CREATE_EMPTY_ELEMENT',
    DELETE_ELEMENT: 'DELETE_ELEMENT',
};
